import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SessionDetail } from "../medical-agent/[sessionId]/page";
import moment from "moment";

type Props = {
  record: SessionDetail;
};

function ViewReportDialog({ record }: Props) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl w-full max-h-[90vh] overflow-y-auto rounded-md sm:max-w-xl">
        <DialogHeader>
          <DialogTitle asChild>
            <h2 className="text-center text-xl font-semibold text-blue-700">
              🩺 Medical AI Voice Agent Report
            </h2>
          </DialogTitle>
        </DialogHeader>

        <DialogDescription asChild>
          <div className="space-y-5 text-sm text-gray-800 px-2 py-1">
            {/* Session Info */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Session Info</h3>
              <hr className="my-1 border-blue-500" />
              <div className="grid grid-cols-2 gap-2 mt-2">
                <p><span className="font-semibold">Doctor:</span> {record?.selectedDoctor?.specialist}</p>
                <p><span className="font-semibold">User:</span> Anonymous</p>
                <p><span className="font-semibold">Consulted On:</span> {moment(record?.createdOn).format("MMMM Do YYYY, h:mm a")}</p>
                <p><span className="font-semibold">Agent:</span> {record?.agent}</p>    
              </div>
            </div>

            {/* Chief Complaint */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Chief Complaint</h3>
              <hr className="my-1 border-blue-500" />
              <p className="mt-2">{record?.chiefComplaint}</p>
            </div>

            {/* Summary */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Summary</h3>
              <hr className="my-1 border-blue-500" />
              <p className="mt-2">
                The user is experiencing sharp back pain. The AI assistant recommended over-the-counter pain relievers like ibuprofen or acetaminophen, emphasizing the importance of following dosage instructions. It also advised consulting a healthcare provider if the pain persists or worsens.
              </p>
            </div>

            {/* Symptoms */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Symptoms</h3>
              <hr className="my-1 border-blue-500" />
              <ul className="list-disc ml-5 mt-2 space-y-1">
                <li>back pain</li>
                <li>sharp pain</li>
              </ul>
            </div>

            {/* Duration & Severity */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Duration & Severity</h3>
              <hr className="my-1 border-blue-500" />
              <div className="grid grid-cols-2 mt-2">
                <p><span className="font-semibold">Duration:</span> Not specified</p>
                <p><span className="font-semibold">Severity:</span> Moderate</p>
              </div>
            </div>

            {/* Medications Mentioned */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Medications Mentioned</h3>
              <hr className="my-1 border-blue-500" />
              <ul className="list-disc ml-5 mt-2 space-y-1">
                <li>ibuprofen</li>
                <li>acetaminophen</li>
              </ul>
            </div>

            {/* Recommendations */}
            <div>
              <h3 className="font-semibold text-md text-blue-700">Recommendations</h3>
              <hr className="my-1 border-blue-500" />
              <ul className="list-disc ml-5 mt-2 space-y-1">
                <li>Try over-the-counter pain relievers (ibuprofen or acetaminophen)</li>
                <li>Follow dosage instructions carefully</li>
                <li>Consult a healthcare provider if pain persists or worsens</li>
              </ul>
            </div>

            {/* Footer */}
            <p className="text-xs text-center text-gray-500 pt-3">
              This report was generated by an AI Medical Assistant for informational purposes only.
            </p>
          </div>
        </DialogDescription>
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;
